- hosts: all
  roles: 
    - name: configure kubernetes cluster and master
      role: k8s_cluster

- hosts: tag_Name_k8s_Master
  roles: 
    - name: Launch Wordpress 
      role: wordpress-mysql-k8s
