- name: "Slave setup"
  pause:    
    prompt: "Do you want to continue slave setup "

- name: join slave to master node
  shell: "{{ master_token.stdout }}"
  ignore_errors: yes 
  register: slave_output 

- debug:
    var: slave_output.stdout_lines 