apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mywp
  name: mywp
spec:
  containers:
  - image: wordpress:5.1.1-php7.3-apache
    name: mywp
    #resources: {}
  restartPolicy: Always
  #status: {}